# Generated by Django 5.1.7 on 2025-04-20 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_productgallary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductGallary',
            new_name='ProductGallery',
        ),
    ]
