[phases.setup]
aptPkgs = ["build-essential", "python3-dev"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "gunicorn greatkart.wsgi:application --bind 0.0.0.0:${PORT}"
